name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        coverage: xdebug

    - name: Validate Composer
      run: composer validate --strict

    - name: Install Composer Dependencies 
      run: composer install --no-interaction --prefer-source
    
    - name: Run Tests
      run: composer pipeline
      env: 
        STRYKER_DASHBOARD_API_KEY: oaOExVMXXbPswvGD2IfSM1t9iVybKhui5C4LyoVwvSoyWmkZU2YmS5Yf7Z2oCjbjzTq6b20iswVjlfakrgd2IzlvpvELu7N/jgPylfKLmG4/mvOxK53FujILsOYd8Np90zlvJb4fRcxYp/iHAmJpJEVz6J7keoRFLR8JVyF7TmbNah40Bog2pG6KaNgQ1xabGTRNDf8Vo6SJtMNrgDxv2LBLBY566QTXH8fuTmijkqsVM/r/N49Pa+2EnE26O4t25HJsBDmEbRWWHAxw7SMxrneLG98dg/GqjroqOJ5h2S2ud3I6l2kI8wtKp0bcosMiijcTZ+z7J9STrrzPIVRLVHYrLQ38+N4FaaS94k87Hk0Ywin4gPqLWU9cTtb/R4/3bE25rGTnxn/Gdm6RtniexcMDcqyjqfv65Iq5RX/mTyIDpFRNUn7M22KitTp/7jULZIVtOgHOxd27TseKgOUcPt8OavPsaakb5voL+aCWZMov1kE6H3p5ZsoDyaMusb4sJHFt63aGegtTrm4cjHKU0qO9L7y/ivI9tK/lVenUbzy+Drt5Jdp40jD5AQ8kxvB96QkxZa6DeFkidl0chwC/GgMSWx9lEMHhO5G0RJAWqWgp+wDBl+u0Wki6NlmPdlk72EbjzSWarK5ddhwElO2QTWGumw+AzfmYUNZiwQr/fJo=

    - name: Code Coverage
      run: bash <(curl -s https://codecov.io/bash)
